### ISSUE TITLE
未能顺利运行

### ISSUE THREAD

**Issue by Xm798** [baranwang/icopy-docker#1]
使用 `wget https://git.io/JJ0V7 -O icopy.sh && bash ./icopy.sh`安装，未能正常运行。
docker日志提示：
```
icopy.sh: 9: cd: can't cd to /app/accounts/
Traceback (most recent call last):
  File "iCopy.py", line 7, in <module>
    from utils import load
  File "/app/iCopy/utils/load.py", line 41, in <module>
    all_drive = gdrive.GoogleDrive().drive_list()
  File "/app/iCopy/drive/gdrive.py", line 18, in __init__
    service_account_file = random.choice(glob(load.cfg['general']['sa_path'] + '/*.json')
  File "/usr/lib/python3.6/random.py", line 260, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
```
配置文件
```
SA_TYPE=local
SA_DIR=/root/sa
SA_GIT_URL=

TG_TOKEN=117745XXXX:AAXXXXXXXXXXXXXXXw
TG_ID=MXXXXXXy_bot

DB_CONNECT_METHOD=mongodb
DB_ADDR=localhost
DB_PORT=27017
DB_NAME=iCopy
DB_USER=kXXXX
DB_PASSWD=kXXXX

BOT_LANGUAGE=cn
PARALLEL_CHECKERS=512
PARALLEL_TRANSFERS=1024
MIN_SLEEP=1ms
```

**Comment by Xm798** [comment]
多次尝试，均无法运行。本次日志和使用的配置如下。
```
Cloning into 'accounts'...
/usr/local/lib/python3.6/dist-packages/telegram/ext/conversationhandler.py:220: UserWarning: If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
  warnings.warn("If 'per_message=False', 'CallbackQueryHandler' will not be "
```

```
SA_TYPE=git
SA_GIT_URL=https://USER:XXXXXXXXXXXXX@github.com/XXXXX/XXXXX

TG_TOKEN=1177XXXXXXXX:AAXXXXXXXXXXXXXXXXXXXsw
TG_ID=MXXXXXXXXt

DB_CONNECT_METHOD=mongodb+srv
DB_ADDR=cluster0.XXXXX.gcp.mongodb.net
DB_PORT=27017
DB_NAME=iCopy
DB_USER=nXXXXX
DB_PASSWD=zXXXXXXXXXXd

BOT_LANGUAGE=cn
PARALLEL_CHECKERS=512
PARALLEL_TRANSFERS=1024
MIN_SLEEP=1ms
```
